version: "2.2"
services:
     mysql:
        image: mysql:5.7.20
        container_name: interview
        restart: always
        volumes:
            - ./data/mysql/:/var/lib/mysql
            - ./data/backup:/opt
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=mrs
        ports:
            - "3301:3306"
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp                        
        networks: 
            - lan
     client:
       image: petersimendi/screening-app:v1.0
       container_name: client
       restart: always
       ports:
         - "8091:8091"
       depends_on:
        - mysql
        - hapi
       networks:
         - lan
     server:
       image:  petersimendi/mock-server:v1.0
       container_name: client
       restart: always
       ports:
         - "8092:8092"
       depends_on:
         - grafana
       networks:
         - lan

     hapi:
       image: hapiproject/hapi:latest
       container_name: hapi
       restart: always
       volumes:
         - ./data/hapi:/usr/local/tomcat/webapps/hapi-fhir-jpaserver-example/WEB-INF/classes/hapi.properties
       ports:
         - "8082:8080"
       networks:
         - lan

     grafana:
      image: grafana/grafana:latest
      ports:
        - 3000:3000
      restart: unless-stopped
      environment:
        - "GF_SECURITY_ADMIN_PASSWORD=admin"
      volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana_data:/var/lib/grafana
      networks:
        - lan

volumes:
  grafana_data:

networks: 
    lan:
        name: interview.net
        driver: bridge  

